name: Aclio
options:
  bundleIdPrefix: com.ahmed
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "2.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  Aclio:
    type: application
    platform: iOS
    sources:
      - path: Aclio/Theme
        group: Theme
      - path: Aclio/Models
        group: Models
      - path: Aclio/Services
        group: Services
      - path: Aclio/Utils
        group: Utils
      - path: Aclio/Components
        group: Components
      - path: Aclio/Screens
        group: Screens
      - path: Aclio/AclioApp.swift
      - path: Aclio/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Aclio/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ahmed.aclio
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        SUPPORTS_MACCATALYST: false
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"

